### ISSUE TITLE
Manual way to set ip of fritzbox

### ISSUE THREAD

**Issue by Technikte** [mxschmitt/fritzbox_exporter#13]
Is there an manual way to set the ip of the fritzbox via docker variable or so ?

This error I get because I using a other dns server which can not resolve fritz.box.

`cannot load services: could not load root element: could not get igddesc.xml: Get http://fritz.box:49000/igddesc.xml: dial tcp: lookup fritz.box on 1.1.1.1:53: no such host`

**Comment by mxschmitt** [comment]
Yes, you can use the following parameter which is per default `fritz.box`:
https://github.com/mxschmitt/fritzbox_exporter/blob/b6069d21e7fb98a0852a550bd9a14493ca3af9f0/cmd/exporter/exporter.go#L357

**Comment by Technikte** [comment]
Yes, sure. But any way to do this with the prebuilt docker image ?

**Comment by mxschmitt** [comment]
Just pass the `--gateway-address`  as a commamd.
