### ISSUE TITLE
set env variables

### ISSUE THREAD

**Issue by GM-Ant** [mxschmitt/fritzbox_exporter#18]
Hi, thanks for the great work!!

My Fritz!Box is however not reachable on its default address so it would be very practical if the next values could be set through docker "ENV" variables:

```
	flag.StringVar(&settings.FritzBox.IP, "gateway-address", "fritz.box", "The hostname or IP of the FRITZ!Box")
	flag.IntVar(&settings.FritzBox.Port, "gateway-port", 49000, "The port of the FRITZ!Box UPnP service")
	flag.StringVar(&settings.FritzBox.UserName, "username", "", "The user for the FRITZ!Box UPnP service")
	flag.StringVar(&settings.FritzBox.Password, "password", "", "The password for the FRITZ!Box UPnP service")
```

**Comment by ilmanzo** [comment]
I understand it's already possible to pass config via ENV ?

https://github.com/mxschmitt/fritzbox_exporter/blob/master/cmd/exporter/exporter.go#L341

**Comment by mxschmitt** [comment]
Good point, yep indeed. It should.
