### ISSUE TITLE
How to connect to Grafana Dashboard?

### ISSUE THREAD

**Issue by JuXReal** [mxschmitt/fritzbox_exporter#23]
Hello, sorry I know this is not a "issue" more a question. 

I can start the Docker Container, he is up and running.  I can see my telemetrics. 

But If I try to connect the grafana Dashboard with Prometheus it doesent work.

Can someone told me, wich data I have to enter in the Grafana Part to get it work?

**Comment by mxschmitt** [comment]
Hi, please use official resources how Grafana and Prometheus work together and how you build on top of that using the fritzbox exporter your own dashboard.

This repo is only for exporter specific bugs.

Thanks!
