### ISSUE TITLE
main.go missing

### ISSUE THREAD

**Issue by foscoj** [mxschmitt/fritzbox_exporter#5]
Hi, after your merge and added .gitignore on Oct 16, the repo seems to be broken, at least from the point of view from the forked one, so it cannot be built anymore.

**Comment by mxschmitt** [comment]
Hi, I changed the project structure a bit, so the main pkg is in the cmd folder: https://github.com/mxschmitt/fritzbox_exporter/blob/master/cmd/exporter/exporter.go
