### ISSUE TITLE
Docker docs

### ISSUE THREAD

**Issue by mgrundkoetter** [mxschmitt/fritzbox_exporter#6]
How is the docker image at https://hub.docker.com/r/mxschmitt/fritzbox_exporter supposed to work? I just started the container, but calling it on port 9133 from the browser does not give any output. Can you please provide your docker call with params in the docs?

**Comment by mxschmitt** [comment]
Have you tried to use the /metrics endpoint?

**Comment by mgrundkoetter** [comment]
You are right, the endpoint works, just calling the container results in nothing (which is kind of expected :-)
I added some lines to the readme.
